- name: include os-specific variables 
  include_vars: "{{ ansible_os_family }}.yml"
  
- name: define apache_packages 
  set_fact: 
    apache_packages: "{{ apache_packages | list }}"  
  when: apache_packages is not defined 

- include_tasks: "{{ ansible_os_family  }}-install.yml"  

- name: ensure apache has selected state and enabled on boot
  service: 
    name: "{{ apache_service }}"
    state: "{{ apache_state }}"
    enabled: true 

    